# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_text',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
