# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_item_item_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_text',
        ),
    ]
